import React,{useMemo,useState} from 'react';
import { SKYFALL_ATTRIBUTES, SKYFALL_SKILLS, SKYFALL_MAGIC_LAYERS } from '../data.js';

const tabs=[['perfil','Identidade'],['status','Status & Combate'],['pericias','Perícias'],['poderes','Habilidades'],['magias','Magias'],['inventario','Inventário']];
const num=v=>Number(v)||0;
const mod=v=>{const n=Math.floor((num(v)-10)/2);return n>=0?`+${n}`:`${n}`;};

export default function SkyfallCharacterEditor({scope}){
 const {data,updateField,setData,optimizeImageFile,showToast}=scope;
 const [tab,setTab]=useState('perfil');
 if(data?.system!=='skyfall'||data?.type!=='pc')return null;
 const patch=(field,i,key,value)=>{const d=JSON.parse(JSON.stringify(data));const arr=Array.isArray(d[field])?d[field]:[];arr[i]={...(arr[i]||{}),[key]:value};d[field]=arr;setData(d);};
 const add=(field,obj)=>updateField(field,[...(data[field]||[]),obj]);
 const remove=(field,i)=>updateField(field,(data[field]||[]).filter((_,x)=>x!==i));
 const move=(field,i,dir)=>{const arr=[...(data[field]||[])];const j=i+dir;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];updateField(field,arr);};
 const photo=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{updateField('bio.imagem',await optimizeImageFile(f,900,.82));showToast('Retrato atualizado.');}catch{showToast('Não foi possível usar esta imagem.');}};
 const a=data.atributos||{},r=data.recursos||{},b=data.bio||{},c=data.combate||{},cj=data.conjuracao||{};
 const magiasPorCamada=useMemo(()=>Object.fromEntries(SKYFALL_MAGIC_LAYERS.map(layer=>[layer,(data.magias||[]).map((m,i)=>({m,i})).filter(({m})=>(m.camada||'Truque')===layer)])),[data.magias]);
 const pair=(key,label)=><div className="skyfall-resource"><span className="skyfall-label">{label}</span><div className="skyfall-pair"><input type="number" value={r[key]?.atual??0} onChange={e=>updateField(`recursos.${key}.atual`,num(e.target.value))}/><span>/</span><input type="number" value={r[key]?.max??0} onChange={e=>updateField(`recursos.${key}.max`,num(e.target.value))}/></div><small>Atual / Máx.</small></div>;
 return <div className="skyfall-sheet p-3 sm:p-5">
  <div className="skyfall-hero"><div><div className="skyfall-kicker">Skyfall RPG • Livro Básico 1.25</div><h2>Ficha de Personagem</h2><p>Fantasia trágica • Catarse • Ênfase • Sombra</p></div><div className="skyfall-level"><span>Nível</span><input type="number" min="1" value={b.nivel||1} onChange={e=>updateField('bio.nivel',Math.max(1,num(e.target.value)))}/></div></div>
  <div className="skyfall-tabs">{tabs.map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}>{n}</button>)}</div>

  {tab==='perfil'&&<div className="space-y-4">
   <section className="skyfall-card"><div className="skyfall-profile-grid"><div className="skyfall-photo">{b.imagem?<img src={b.imagem} alt="Retrato"/>:<div className="skyfall-photo-empty">☄️</div>}<label>Escolher imagem<input type="file" accept="image/*" className="hidden" onChange={photo}/></label>{b.imagem&&<button onClick={()=>updateField('bio.imagem','')}>Remover</button>}</div><div className="grid sm:grid-cols-2 gap-3">
    <label className="sm:col-span-2"><span>Nome da Personagem</span><input value={b.nome||''} onChange={e=>updateField('bio.nome',e.target.value)}/></label>
    <label><span>Jogadore</span><input value={b.jogador||''} onChange={e=>updateField('bio.jogador',e.target.value)}/></label><label><span>Pronomes</span><input value={b.pronomes||''} onChange={e=>updateField('bio.pronomes',e.target.value)}/></label>
    <label><span>Legado</span><input value={b.legado||''} onChange={e=>updateField('bio.legado',e.target.value)}/></label><label><span>Herança</span><input value={b.heranca||''} onChange={e=>updateField('bio.heranca',e.target.value)}/></label>
    <label><span>Antecedente</span><input value={b.antecedente||''} onChange={e=>updateField('bio.antecedente',e.target.value)}/></label><label><span>Maldição</span><input value={b.maldicao||''} onChange={e=>updateField('bio.maldicao',e.target.value)}/></label>
    <label><span>Classe</span><input value={b.classe||''} onChange={e=>updateField('bio.classe',e.target.value)}/></label><label><span>Trilha</span><input value={b.trilha||''} onChange={e=>updateField('bio.trilha',e.target.value)}/></label>
    <label className="sm:col-span-2"><span>Melancolia</span><textarea rows="3" value={b.melancolia||''} onChange={e=>updateField('bio.melancolia',e.target.value)}/></label>
   </div></div></section>
   <section className="skyfall-card"><h3>Atributos</h3><div className="skyfall-attributes">{SKYFALL_ATTRIBUTES.map(([k,abbr,n])=><label key={k} className="skyfall-attr"><span>{abbr}</span><input type="number" value={a[k]??10} onChange={e=>updateField(`atributos.${k}`,num(e.target.value))}/><small>{mod(a[k])}</small><em>{n}</em></label>)}</div></section>
  </div>}

  {tab==='status'&&<div className="space-y-4">
   <section className="skyfall-card"><div className="skyfall-section-head"><div><h3>Status & Recursos</h3><p className="skyfall-help">Organizado como o núcleo da ficha oficial: vida, Catarse, Ênfase, Sombra e recursos de aventura.</p></div></div><div className="skyfall-resource-grid">{pair('pv','PV')}{pair('catarse','Catarse')}{pair('enfase','Ênfase')}<label className="skyfall-resource"><span>Pontos de Sombra</span><input type="number" value={r.sombra??0} onChange={e=>updateField('recursos.sombra',num(e.target.value))}/></label>{pair('fragmentos','Fragmentos Arcanos')}{pair('volume','Volume de Carga')}<label className="skyfall-resource"><span>PV Temporários</span><input type="number" value={r.pv?.temp??0} onChange={e=>updateField('recursos.pv.temp',num(e.target.value))}/></label><label className="skyfall-resource"><span>Bônus de Proficiência</span><input type="number" value={data.proficiencia??2} onChange={e=>updateField('proficiencia',num(e.target.value))}/></label><div className="skyfall-resource"><span className="skyfall-label">Dados de Vida</span><div className="skyfall-pair"><input value={r.dadosVida?.usados??''} onChange={e=>updateField('recursos.dadosVida.usados',e.target.value)} placeholder="Usados"/><span>/</span><input value={r.dadosVida?.totais??''} onChange={e=>updateField('recursos.dadosVida.totais',e.target.value)} placeholder="Totais"/></div></div><div className="skyfall-resource"><span className="skyfall-label">Testes de Morte</span><div className="skyfall-pair"><input type="number" min="0" value={r.testesMorte?.sucessos??0} onChange={e=>updateField('recursos.testesMorte.sucessos',num(e.target.value))}/><span>✓ / ✕</span><input type="number" min="0" value={r.testesMorte?.falhas??0} onChange={e=>updateField('recursos.testesMorte.falhas',num(e.target.value))}/></div></div></div></section>
   <section className="skyfall-card"><h3>Defesa & Movimento</h3><div className="skyfall-combat-grid">{[['protecao','Proteção'],['reducaoDano','Redução de Dano'],['iniciativa','Iniciativa'],['tamanho','Tamanho'],['deslocamento','Deslocamento']].map(([k,n])=><label key={k}><span>{n}</span><input value={c[k]||''} onChange={e=>updateField(`combate.${k}`,e.target.value)}/></label>)}</div></section>
   <section className="skyfall-card"><div className="skyfall-section-head"><div><h3>Ataques</h3><p className="skyfall-help">Use ↑ ↓ para ordenar na mesma sequência em que você consulta em mesa.</p></div><button className="skyfall-add" onClick={()=>add('ataques',{nome:'',bonus:'',dano:'',tipo:'',alcance:'',descricao:''})}>+ Ataque</button></div><div className="space-y-2">{(data.ataques||[]).map((x,i)=><div key={i} className="skyfall-entry skyfall-attack"><div className="skyfall-attack-main"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome do ataque"/><input value={x.bonus||''} onChange={e=>patch('ataques',i,'bonus',e.target.value)} placeholder="Bônus"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><input value={x.alcance||''} onChange={e=>patch('ataques',i,'alcance',e.target.value)} placeholder="Alcance"/></div><div className="skyfall-attack-detail"><input value={x.tipo||''} onChange={e=>patch('ataques',i,'tipo',e.target.value)} placeholder="Descritores / tipo"/><textarea rows="2" value={x.descricao||x.notas||''} onChange={e=>patch('ataques',i,'descricao',e.target.value)} placeholder="Descrição, efeito ou lembrete"/></div><div className="skyfall-sort"><button disabled={i===0} onClick={()=>move('ataques',i,-1)} title="Mover para cima">↑</button><button disabled={i===(data.ataques||[]).length-1} onClick={()=>move('ataques',i,1)} title="Mover para baixo">↓</button><button className="danger" onClick={()=>remove('ataques',i)} title="Remover">×</button></div></div>)}</div></section>
  </div>}

  {tab==='pericias'&&<section className="skyfall-card"><h3>Perícias</h3><p className="skyfall-help">Marque proficiência e Ênfase; o bônus livre serve para ajustes da ficha ou da mesa.</p><div className="skyfall-skills-grid">{SKYFALL_SKILLS.map(([id,n,attr])=>{const x=data.pericias?.[id]||{};return <div key={id} className="skyfall-skill"><div><strong>{n}</strong><small>{attr.toUpperCase()}</small></div><label><input type="checkbox" checked={!!x.proficiente} onChange={e=>updateField(`pericias.${id}.proficiente`,e.target.checked)}/> Prof.</label><label><input type="checkbox" checked={!!x.enfase} onChange={e=>updateField(`pericias.${id}.enfase`,e.target.checked)}/> Ênfase</label><input value={x.bonus||''} onChange={e=>updateField(`pericias.${id}.bonus`,e.target.value)} placeholder="+0"/></div>})}</div></section>}

  {tab==='poderes'&&<section className="skyfall-card"><div className="skyfall-section-head"><h3>Habilidades</h3><button className="skyfall-add" onClick={()=>add('habilidades',{nome:'',origem:'',desc:''})}>+ Habilidade</button></div><div className="grid md:grid-cols-2 gap-2">{(data.habilidades||[]).map((x,i)=><div key={i} className="skyfall-entry"><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>remove('habilidades',i)}>×</button></div><input value={x.origem||''} onChange={e=>patch('habilidades',i,'origem',e.target.value)} placeholder="Origem"/><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)} placeholder="Descrição / lembrete"/></div>)}</div></section>}

  {tab==='magias'&&<div className="space-y-4">
   <section className="skyfall-card skyfall-caster-panel"><div><div className="skyfall-kicker">Painel de Conjuração</div><h3>Arcanum</h3><p className="skyfall-help">A ficha oficial destaca Atributo‑Chave e Bônus de Ataque; aqui eles ficam sempre visíveis para consulta rápida.</p></div><div className="skyfall-caster-grid"><label><span>Atributo‑Chave</span><input value={cj.atributoChave||''} onChange={e=>updateField('conjuracao.atributoChave',e.target.value)} placeholder="INT, SAB..."/></label><label><span>Bônus de Ataque</span><input value={cj.bonusAtaque||''} onChange={e=>updateField('conjuracao.bonusAtaque',e.target.value)} placeholder="+0"/></label><label><span>CD / dificuldade</span><input value={cj.cd||''} onChange={e=>updateField('conjuracao.cd',e.target.value)} placeholder="Opcional"/></label><div className="skyfall-caster-summary"><span>Nível {b.nivel||1}</span><span>{b.classe||'Sem classe'}</span><span>{b.trilha||'Sem trilha'}</span></div></div></section>
   {SKYFALL_MAGIC_LAYERS.map(layer=><section className="skyfall-card skyfall-magic-section" key={layer}><div className="skyfall-section-head"><div><h3>{layer==='Truque'?'Truques Mágicos':`Camada ${layer}`}</h3><p className="skyfall-help">{magiasPorCamada[layer].length} magia{magiasPorCamada[layer].length===1?'':'s'} registrada{magiasPorCamada[layer].length===1?'':'s'}.</p></div><button className="skyfall-add" onClick={()=>add('magias',{nome:'',camada:layer,custo:'',execucao:'',alcance:'',duracao:'',descritores:'',desc:''})}>+ Magia</button></div><div className="grid md:grid-cols-2 gap-2">{magiasPorCamada[layer].map(({m,i})=><div key={i} className="skyfall-entry skyfall-spell"><div className="flex gap-2"><input className="flex-1 font-bold" value={m.nome||''} onChange={e=>patch('magias',i,'nome',e.target.value)} placeholder="Nome da magia"/><button onClick={()=>remove('magias',i)}>×</button></div><div className="grid grid-cols-2 gap-2"><select value={m.camada||layer} onChange={e=>patch('magias',i,'camada',e.target.value)}>{SKYFALL_MAGIC_LAYERS.map(x=><option key={x}>{x}</option>)}</select><input value={m.custo||''} onChange={e=>patch('magias',i,'custo',e.target.value)} placeholder="Custo / PE"/><input value={m.execucao||''} onChange={e=>patch('magias',i,'execucao',e.target.value)} placeholder="Execução"/><input value={m.alcance||''} onChange={e=>patch('magias',i,'alcance',e.target.value)} placeholder="Alcance"/><input value={m.duracao||''} onChange={e=>patch('magias',i,'duracao',e.target.value)} placeholder="Duração"/><input value={m.descritores||''} onChange={e=>patch('magias',i,'descritores',e.target.value)} placeholder="Descritores"/></div><textarea rows="3" value={m.desc||''} onChange={e=>patch('magias',i,'desc',e.target.value)} placeholder="Efeito / lembrete"/></div>)}</div></section>)}
   <section className="skyfall-card"><label><span>Observações de Conjuração</span><textarea rows="4" value={cj.observacoes||''} onChange={e=>updateField('conjuracao.observacoes',e.target.value)} placeholder="Componentes, limitações, sinergias ou lembretes de mesa"/></label></section>
  </div>}

  {tab==='inventario'&&<div className="space-y-4"><section className="skyfall-card"><div className="skyfall-section-head"><h3>Equipamentos</h3><button className="skyfall-add" onClick={()=>add('equipamentos',{nome:'',quantidade:1,volume:'',fragmentos:'',descritores:''})}>+ Item</button></div><div className="space-y-2">{(data.equipamentos||[]).map((x,i)=><div key={i} className="skyfall-entry"><div className="skyfall-item-grid"><input value={x.nome||''} onChange={e=>patch('equipamentos',i,'nome',e.target.value)} placeholder="Item"/><input type="number" value={x.quantidade??1} onChange={e=>patch('equipamentos',i,'quantidade',num(e.target.value))}/><input value={x.volume||''} onChange={e=>patch('equipamentos',i,'volume',e.target.value)} placeholder="Vol."/><input value={x.fragmentos||''} onChange={e=>patch('equipamentos',i,'fragmentos',e.target.value)} placeholder="Frag."/><button onClick={()=>remove('equipamentos',i)}>×</button></div><input value={x.descritores||''} onChange={e=>patch('equipamentos',i,'descritores',e.target.value)} placeholder="Descritores"/></div>)}</div></section><section className="skyfall-card"><div className="grid sm:grid-cols-3 gap-3"><label><span>Peças</span><input type="number" value={data.moedas?.pecas??0} onChange={e=>updateField('moedas.pecas',num(e.target.value))}/></label><label><span>Trocados</span><input type="number" value={data.moedas?.trocados??0} onChange={e=>updateField('moedas.trocados',num(e.target.value))}/></label><label><span>Idiomas e outras proficiências</span><input value={data.idiomas||''} onChange={e=>updateField('idiomas',e.target.value)}/></label></div><label className="block mt-3"><span>Anotações</span><textarea rows="6" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section></div>}
 </div>;
}
