import React, { useState } from 'react';
import { SKYFALL_ATTRIBUTES, SKYFALL_SKILLS } from '../data.js';

const tabs=[['perfil','Perfil'],['pericias','Perícias'],['combate','Combate'],['poderes','Habilidades & Magias'],['inventario','Inventário']];
const num=v=>Number(v)||0;
const mod=v=>{const n=Math.floor((num(v)-10)/2);return n>=0?`+${n}`:`${n}`;};

export default function SkyfallCharacterEditor({scope}){
 const {data,updateField,setData,optimizeImageFile,showToast}=scope; const [tab,setTab]=useState('perfil');
 if(data?.system!=='skyfall'||data?.type!=='pc')return null;
 const patch=(field,i,key,value)=>{const d=JSON.parse(JSON.stringify(data));const arr=Array.isArray(d[field])?d[field]:[];arr[i]={...(arr[i]||{}),[key]:value};d[field]=arr;setData(d);};
 const add=(field,obj)=>updateField(field,[...(data[field]||[]),obj]), remove=(field,i)=>updateField(field,(data[field]||[]).filter((_,x)=>x!==i));
 const photo=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{updateField('bio.imagem',await optimizeImageFile(f,900,.82));showToast('Retrato atualizado.');}catch{showToast('Não foi possível usar esta imagem.');}};
 const a=data.atributos||{},r=data.recursos||{},b=data.bio||{},c=data.combate||{};
 return <div className="skyfall-sheet p-3 sm:p-5">
  <div className="skyfall-hero"><div><div className="skyfall-kicker">Skyfall RPG • Livro Básico 1.25</div><h2>Ficha de Personagem</h2><p>Fantasia trágica • Catarse • Ênfase • Sombra</p></div><div className="skyfall-level"><span>Nível</span><input type="number" min="1" value={b.nivel||1} onChange={e=>updateField('bio.nivel',Math.max(1,num(e.target.value)))}/></div></div>
  <div className="skyfall-tabs">{tabs.map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}>{n}</button>)}</div>
  {tab==='perfil'&&<div className="space-y-4">
   <section className="skyfall-card"><div className="grid md:grid-cols-[150px_1fr] gap-4"><div className="skyfall-photo">{b.imagem?<img src={b.imagem} alt="Retrato"/>:<div className="skyfall-photo-empty">☄️</div>}<label>Escolher imagem<input type="file" accept="image/*" className="hidden" onChange={photo}/></label>{b.imagem&&<button onClick={()=>updateField('bio.imagem','')}>Remover</button>}</div><div className="grid sm:grid-cols-2 gap-3">
    <label className="sm:col-span-2"><span>Nome da Personagem</span><input value={b.nome||''} onChange={e=>updateField('bio.nome',e.target.value)}/></label>
    <label><span>Jogadore</span><input value={b.jogador||''} onChange={e=>updateField('bio.jogador',e.target.value)}/></label><label><span>Pronomes</span><input value={b.pronomes||''} onChange={e=>updateField('bio.pronomes',e.target.value)}/></label>
    <label><span>Legado</span><input value={b.legado||''} onChange={e=>updateField('bio.legado',e.target.value)}/></label><label><span>Herança</span><input value={b.heranca||''} onChange={e=>updateField('bio.heranca',e.target.value)}/></label>
    <label><span>Antecedente</span><input value={b.antecedente||''} onChange={e=>updateField('bio.antecedente',e.target.value)}/></label><label><span>Maldição</span><input value={b.maldicao||''} onChange={e=>updateField('bio.maldicao',e.target.value)}/></label>
    <label><span>Classe</span><input value={b.classe||''} onChange={e=>updateField('bio.classe',e.target.value)}/></label><label><span>Trilha</span><input value={b.trilha||''} onChange={e=>updateField('bio.trilha',e.target.value)}/></label>
    <label className="sm:col-span-2"><span>Melancolia</span><textarea rows="2" value={b.melancolia||''} onChange={e=>updateField('bio.melancolia',e.target.value)}/></label>
   </div></div></section>
   <section className="skyfall-card"><h3>Atributos</h3><div className="grid grid-cols-3 md:grid-cols-6 gap-2">{SKYFALL_ATTRIBUTES.map(([k,abbr,n])=><label key={k} className="skyfall-attr"><span>{abbr}</span><input type="number" value={a[k]??10} onChange={e=>updateField(`atributos.${k}`,num(e.target.value))}/><small>{mod(a[k])}</small><em>{n}</em></label>)}</div></section>
   <section className="skyfall-card"><h3>Recursos principais</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><label><span>Proficiência</span><input type="number" value={data.proficiencia??2} onChange={e=>updateField('proficiencia',num(e.target.value))}/></label>{['pv','catarse','enfase'].map(k=><div key={k}><span className="skyfall-label">{k==='pv'?'PV':k==='catarse'?'Catarse':'Ênfase'}</span><div className="grid grid-cols-2 gap-1"><input type="number" value={r[k]?.atual??0} onChange={e=>updateField(`recursos.${k}.atual`,num(e.target.value))}/><input type="number" value={r[k]?.max??0} onChange={e=>updateField(`recursos.${k}.max`,num(e.target.value))}/></div><small>Atual / Máx.</small></div>)}<label><span>Pontos de Sombra</span><input type="number" value={r.sombra??0} onChange={e=>updateField('recursos.sombra',num(e.target.value))}/></label><div><span className="skyfall-label">Fragmentos Arcanos</span><div className="grid grid-cols-2 gap-1"><input type="number" value={r.fragmentos?.atual??0} onChange={e=>updateField('recursos.fragmentos.atual',num(e.target.value))}/><input type="number" value={r.fragmentos?.max??0} onChange={e=>updateField('recursos.fragmentos.max',num(e.target.value))}/></div></div><div><span className="skyfall-label">Volume de carga</span><div className="grid grid-cols-2 gap-1"><input type="number" value={r.volume?.atual??0} onChange={e=>updateField('recursos.volume.atual',num(e.target.value))}/><input type="number" value={r.volume?.max??0} onChange={e=>updateField('recursos.volume.max',num(e.target.value))}/></div></div><label><span>PV temporários</span><input type="number" value={r.pv?.temp??0} onChange={e=>updateField('recursos.pv.temp',num(e.target.value))}/></label></div></section>
  </div>}
  {tab==='pericias'&&<section className="skyfall-card"><h3>Perícias</h3><p className="skyfall-help">Marque proficiência e Ênfase; o bônus livre serve para ajustes da ficha ou da mesa.</p><div className="grid sm:grid-cols-2 gap-2 mt-3">{SKYFALL_SKILLS.map(([id,n,attr])=>{const x=data.pericias?.[id]||{};return <div key={id} className="skyfall-skill"><div><strong>{n}</strong><small>{attr.toUpperCase()}</small></div><label><input type="checkbox" checked={!!x.proficiente} onChange={e=>updateField(`pericias.${id}.proficiente`,e.target.checked)}/> Prof.</label><label><input type="checkbox" checked={!!x.enfase} onChange={e=>updateField(`pericias.${id}.enfase`,e.target.checked)}/> Ênfase</label><input className="w-16" value={x.bonus||''} onChange={e=>updateField(`pericias.${id}.bonus`,e.target.value)} placeholder="+0"/></div>})}</div></section>}
  {tab==='combate'&&<div className="space-y-4"><section className="skyfall-card"><h3>Defesa e movimento</h3><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['protecao','Proteção'],['reducaoDano','Redução de dano'],['iniciativa','Iniciativa'],['tamanho','Tamanho'],['deslocamento','Deslocamento']].map(([k,n])=><label key={k}><span>{n}</span><input value={c[k]||''} onChange={e=>updateField(`combate.${k}`,e.target.value)}/></label>)}</div></section><section className="skyfall-card"><div className="flex justify-between"><h3>Ataques</h3><button className="skyfall-add" onClick={()=>add('ataques',{nome:'',bonus:'',dano:'',tipo:'',alcance:'',notas:''})}>+ Ataque</button></div><div className="space-y-2">{(data.ataques||[]).map((x,i)=><div key={i} className="skyfall-row"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome"/><input value={x.bonus||''} onChange={e=>patch('ataques',i,'bonus',e.target.value)} placeholder="Bônus"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><input value={x.alcance||''} onChange={e=>patch('ataques',i,'alcance',e.target.value)} placeholder="Alcance"/><button onClick={()=>remove('ataques',i)}>×</button></div>)}</div></section></div>}
  {tab==='poderes'&&<div className="space-y-4"><section className="skyfall-card"><div className="flex justify-between"><h3>Habilidades</h3><button className="skyfall-add" onClick={()=>add('habilidades',{nome:'',origem:'',desc:''})}>+ Habilidade</button></div><div className="grid md:grid-cols-2 gap-2">{(data.habilidades||[]).map((x,i)=><div key={i} className="skyfall-entry"><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>remove('habilidades',i)}>×</button></div><input value={x.origem||''} onChange={e=>patch('habilidades',i,'origem',e.target.value)} placeholder="Origem"/><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)} placeholder="Descrição / lembrete"/></div>)}</div></section><section className="skyfall-card"><div className="flex justify-between"><h3>Magias</h3><button className="skyfall-add" onClick={()=>add('magias',{nome:'',camada:'',alcance:'',duracao:'',descritores:'',desc:''})}>+ Magia</button></div><div className="grid md:grid-cols-2 gap-2">{(data.magias||[]).map((x,i)=><div key={i} className="skyfall-entry"><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('magias',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>remove('magias',i)}>×</button></div><div className="grid grid-cols-2 gap-2"><input value={x.camada||''} onChange={e=>patch('magias',i,'camada',e.target.value)} placeholder="Camada"/><input value={x.descritores||''} onChange={e=>patch('magias',i,'descritores',e.target.value)} placeholder="Descritores"/></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('magias',i,'desc',e.target.value)} placeholder="Efeito / lembrete"/></div>)}</div></section></div>}
  {tab==='inventario'&&<div className="space-y-4"><section className="skyfall-card"><div className="flex justify-between"><h3>Equipamentos</h3><button className="skyfall-add" onClick={()=>add('equipamentos',{nome:'',quantidade:1,volume:'',fragmentos:'',descritores:''})}>+ Item</button></div><div className="space-y-2">{(data.equipamentos||[]).map((x,i)=><div key={i} className="skyfall-row skyfall-item-row"><input value={x.nome||''} onChange={e=>patch('equipamentos',i,'nome',e.target.value)} placeholder="Item"/><input type="number" value={x.quantidade??1} onChange={e=>patch('equipamentos',i,'quantidade',num(e.target.value))}/><input value={x.volume||''} onChange={e=>patch('equipamentos',i,'volume',e.target.value)} placeholder="Vol."/><input value={x.fragmentos||''} onChange={e=>patch('equipamentos',i,'fragmentos',e.target.value)} placeholder="Frag."/><input value={x.descritores||''} onChange={e=>patch('equipamentos',i,'descritores',e.target.value)} placeholder="Descritores"/><button onClick={()=>remove('equipamentos',i)}>×</button></div>)}</div></section><section className="skyfall-card"><div className="grid sm:grid-cols-3 gap-3"><label><span>Peças</span><input type="number" value={data.moedas?.pecas??0} onChange={e=>updateField('moedas.pecas',num(e.target.value))}/></label><label><span>Trocados</span><input type="number" value={data.moedas?.trocados??0} onChange={e=>updateField('moedas.trocados',num(e.target.value))}/></label><label><span>Idiomas e proficiências</span><input value={data.idiomas||''} onChange={e=>updateField('idiomas',e.target.value)}/></label></div><label className="block mt-3"><span>Anotações</span><textarea rows="6" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section></div>}
 </div>;
}
