import React, { useState } from 'react';
import { SKYFALL_ATTRIBUTES } from '../data.js';
const n=v=>Number(v)||0;
export default function SkyfallThreatEditor({scope}){
 const {data,updateField,setData}=scope; const [tab,setTab]=useState('perfil'); if(data?.system!=='skyfall'||data?.type==='pc')return null;
 const patch=(field,i,key,value)=>{const d=JSON.parse(JSON.stringify(data));const a=Array.isArray(d[field])?d[field]:[];a[i]={...(a[i]||{}),[key]:value};d[field]=a;setData(d);};
 const add=(field,obj)=>updateField(field,[...(data[field]||[]),obj]),rm=(field,i)=>updateField(field,(data[field]||[]).filter((_,x)=>x!==i)); const a=data.atributos||{},s=data.status||{};
 return <div className="skyfall-sheet p-3 sm:p-5"><div className="skyfall-hero skyfall-threat-hero"><div><div className="skyfall-kicker">Skyfall RPG • Modo Mestre</div><h2>Ameaça / PNJ</h2><p>Hierarquia • Arquétipo • ND • Recarga</p></div><div className="skyfall-level"><span>ND</span><input type="number" value={data.nivelDesafio??1} onChange={e=>updateField('nivelDesafio',n(e.target.value))}/></div></div>
  <div className="skyfall-tabs">{[['perfil','Perfil'],['acoes','Ações'],['notas','Notas']].map(([id,x])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{x}</button>)}</div>
  {tab==='perfil'&&<div className="space-y-4"><section className="skyfall-card"><div className="grid sm:grid-cols-2 md:grid-cols-4 gap-3"><label className="sm:col-span-2"><span>Nome</span><input value={data.nome||''} onChange={e=>updateField('nome',e.target.value)}/></label><label><span>Hierarquia</span><input value={data.hierarquia||''} onChange={e=>updateField('hierarquia',e.target.value)}/></label><label><span>Arquétipo</span><input value={data.arquetipo||''} onChange={e=>updateField('arquetipo',e.target.value)}/></label><label><span>Tipo</span><input value={data.tipo||''} onChange={e=>updateField('tipo',e.target.value)}/></label><label><span>Tamanho</span><input value={data.tamanho||''} onChange={e=>updateField('tamanho',e.target.value)}/></label><label><span>XP</span><input type="number" value={data.xp??0} onChange={e=>updateField('xp',n(e.target.value))}/></label><label><span>Recarga</span><input value={data.recarga||''} onChange={e=>updateField('recarga',e.target.value)}/></label><label className="sm:col-span-2 md:col-span-4"><span>Conceito</span><textarea rows="2" value={data.conceito||''} onChange={e=>updateField('conceito',e.target.value)}/></label></div></section><section className="skyfall-card"><h3>Atributos</h3><div className="grid grid-cols-3 md:grid-cols-6 gap-2">{SKYFALL_ATTRIBUTES.map(([k,abbr])=><label key={k} className="skyfall-attr"><span>{abbr}</span><input type="number" value={a[k]??10} onChange={e=>updateField(`atributos.${k}`,n(e.target.value))}/></label>)}</div></section><section className="skyfall-card"><h3>Status</h3><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><div><span className="skyfall-label">PV</span><div className="grid grid-cols-2 gap-1"><input type="number" value={s.pvAtual??0} onChange={e=>updateField('status.pvAtual',n(e.target.value))}/><input type="number" value={s.pvMax??0} onChange={e=>updateField('status.pvMax',n(e.target.value))}/></div></div>{['protecao','reducaoDano','iniciativa','deslocamento'].map(k=><label key={k}><span>{k==='protecao'?'Proteção':k==='reducaoDano'?'RD':k==='iniciativa'?'Iniciativa':'Deslocamento'}</span><input value={s[k]||''} onChange={e=>updateField(`status.${k}`,e.target.value)}/></label>)}</div></section></div>}
  {tab==='acoes'&&<div className="space-y-4"><section className="skyfall-card"><div className="flex justify-between"><h3>Ataques</h3><button className="skyfall-add" onClick={()=>add('ataques',{nome:'',bonus:'',dano:'',alcance:'',desc:''})}>+ Ataque</button></div>{(data.ataques||[]).map((x,i)=><div className="skyfall-entry" key={i}><div className="skyfall-row"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome"/><input value={x.bonus||''} onChange={e=>patch('ataques',i,'bonus',e.target.value)} placeholder="Bônus"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><button onClick={()=>rm('ataques',i)}>×</button></div><textarea rows="2" value={x.desc||''} onChange={e=>patch('ataques',i,'desc',e.target.value)} placeholder="Efeito / observações"/></div>)}</section><section className="skyfall-card"><div className="flex justify-between"><h3>Habilidades</h3><button className="skyfall-add" onClick={()=>add('habilidades',{nome:'',desc:''})}>+ Habilidade</button></div><div className="grid md:grid-cols-2 gap-2">{(data.habilidades||[]).map((x,i)=><div className="skyfall-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)}/><button onClick={()=>rm('habilidades',i)}>×</button></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)}/></div>)}</div></section></div>}
  {tab==='notas'&&<section className="skyfall-card"><div className="grid md:grid-cols-2 gap-3"><label><span>Resistências</span><textarea rows="4" value={data.resistencias||''} onChange={e=>updateField('resistencias',e.target.value)}/></label><label><span>Vulnerabilidades</span><textarea rows="4" value={data.vulnerabilidades||''} onChange={e=>updateField('vulnerabilidades',e.target.value)}/></label></div><label className="block mt-3"><span>Anotações do Mestre</span><textarea rows="8" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section>}
 </div>;
}
