import React,{useState} from 'react';
import { ORDEM_ATTRIBUTES, ORDEM_SKILLS } from '../data.js';
const num=v=>Number(v)||0;
const tabs=[['agente','Agente'],['pericias','Perícias'],['combate','Combate'],['poderes','Poderes & Rituais'],['inventario','Inventário']];
export default function OrdemCharacterEditor({scope}){
 const {data,updateField,setData,optimizeImageFile,showToast}=scope;
 const [tab,setTab]=useState('agente');
 if(data?.system!=='ordemParanormal'||data?.type!=='pc')return null;
 const patch=(field,i,key,value)=>{const d=JSON.parse(JSON.stringify(data));const a=Array.isArray(d[field])?d[field]:[];a[i]={...(a[i]||{}),[key]:value};d[field]=a;setData(d);};
 const add=(f,o)=>updateField(f,[...(data[f]||[]),o]); const rm=(f,i)=>updateField(f,(data[f]||[]).filter((_,x)=>x!==i));
 const photo=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{updateField('bio.imagem',await optimizeImageFile(f,900,.82));showToast('Retrato atualizado.');}catch{showToast('Não foi possível usar esta imagem.');}};
 const b=data.bio||{},a=data.atributos||{},s=data.status||{};
 const pct=(cur,max)=>`${Math.max(0,Math.min(100,(num(cur)/Math.max(1,num(max)))*100))}%`;
 const meter=(kind,label,curKey,maxKey)=><div className={`ordem-meter ordem-meter--${kind}`} style={{'--fill':pct(s[curKey],s[maxKey])}}><span>{label}</span><div className="ordem-meter-fields"><input type="number" value={s[curKey]??0} onChange={e=>updateField(`status.${curKey}`,num(e.target.value))}/><b>/</b><input type="number" value={s[maxKey]??0} onChange={e=>updateField(`status.${maxKey}`,num(e.target.value))}/></div></div>;
 return <div className="ordem-sheet p-3 sm:p-5">
  <div className="ordem-hero"><div><div className="ordem-kicker">Ordem Paranormal RPG • Livro de Regras v1.3</div><h2>Ficha de Agente</h2><p>Painel rápido inspirado na leitura compacta do CRIS, com identidade visual própria do PJLite.</p></div><div className="ordem-nex"><span>NEX</span><div><input type="number" min="0" max="100" value={b.nex??5} onChange={e=>updateField('bio.nex',num(e.target.value))}/><b>%</b></div></div></div>
  <div className="ordem-tabs">{tabs.map(([id,n])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{n}</button>)}</div>

  {tab==='agente'&&<div className="space-y-3">
   <section className="ordem-panel ordem-agent-panel"><div className="ordem-agent-grid"><div className="ordem-photo">{b.imagem?<img src={b.imagem} alt="Retrato"/>:<div className="ordem-photo-empty">△</div>}<label>Escolher imagem<input type="file" accept="image/*" className="hidden" onChange={photo}/></label>{b.imagem&&<button onClick={()=>updateField('bio.imagem','')}>Remover</button>}</div><div className="ordem-identity-grid"><label className="wide"><span>Nome</span><input value={b.nome||''} onChange={e=>updateField('bio.nome',e.target.value)}/></label><label><span>Jogador</span><input value={b.jogador||''} onChange={e=>updateField('bio.jogador',e.target.value)}/></label><label><span>Idade</span><input value={b.idade||''} onChange={e=>updateField('bio.idade',e.target.value)}/></label><label><span>Origem</span><input value={b.origem||''} onChange={e=>updateField('bio.origem',e.target.value)}/></label><label><span>Patente</span><input value={b.patente||''} onChange={e=>updateField('bio.patente',e.target.value)}/></label><label><span>Classe</span><select value={b.classe||''} onChange={e=>updateField('bio.classe',e.target.value)}><option value="">—</option><option>Combatente</option><option>Especialista</option><option>Ocultista</option></select></label><label><span>Trilha</span><input value={b.trilha||''} onChange={e=>updateField('bio.trilha',e.target.value)}/></label></div></div></section>
   <section className="ordem-panel"><div className="ordem-panel-title"><span>ATRIBUTOS</span><small>consulta rápida</small></div><div className="ordem-attrs">{ORDEM_ATTRIBUTES.map(([k,abbr,n])=><label className="ordem-attr" key={k}><span className="ordem-attr-name">{n}</span><input type="number" min="0" value={a[k]??1} onChange={e=>updateField(`atributos.${k}`,num(e.target.value))}/><strong>{abbr}</strong></label>)}</div></section>
   <section className="ordem-panel"><div className="ordem-meters">{meter('vida','VIDA','pvAtual','pvMax')}{meter('sanidade','SANIDADE','sanAtual','sanMax')}{meter('esforco','ESFORÇO','peAtual','peMax')}</div><div className="ordem-derived"><label><span>Defesa</span><input type="number" value={s.defesa??10} onChange={e=>updateField('status.defesa',num(e.target.value))}/></label><label><span>Bloqueio</span><input type="number" value={s.bloqueio??0} onChange={e=>updateField('status.bloqueio',num(e.target.value))}/></label><label><span>Esquiva</span><input type="number" value={s.esquiva??10} onChange={e=>updateField('status.esquiva',num(e.target.value))}/></label><label><span>PE/Rodada</span><input type="number" value={s.peRodada??1} onChange={e=>updateField('status.peRodada',num(e.target.value))}/></label><label><span>Deslocamento</span><input value={s.deslocamento||''} onChange={e=>updateField('status.deslocamento',e.target.value)}/></label><label><span>Afinidade</span><input value={data.afinidade||''} onChange={e=>updateField('afinidade',e.target.value)}/></label></div></section>
  </div>}

  {tab==='pericias'&&<section className="ordem-panel"><div className="ordem-panel-title"><span>PERÍCIAS</span><small>treino e bônus adicionais</small></div><div className="ordem-skill-head"><span>Perícia</span><span>Attr.</span><span>Treino</span><span>Outros</span></div><div className="ordem-skills">{ORDEM_SKILLS.map(([id,n,attr])=>{const x=data.pericias?.[id]||{};return <div className="ordem-skill" key={id}><div><strong>{n}</strong></div><span className="ordem-skill-attr">{attr.toUpperCase()}</span><select value={x.grau??0} onChange={e=>updateField(`pericias.${id}.grau`,num(e.target.value))}><option value="0">0</option><option value="5">+5</option><option value="10">+10</option><option value="15">+15</option></select><input type="number" value={x.outros??0} onChange={e=>updateField(`pericias.${id}.outros`,num(e.target.value))}/></div>})}</div></section>}

  {tab==='combate'&&<div className="space-y-3"><section className="ordem-panel"><div className="ordem-combat-summary"><label><span>Defesa</span><input type="number" value={s.defesa??10} onChange={e=>updateField('status.defesa',num(e.target.value))}/></label><label><span>Bloqueio</span><input type="number" value={s.bloqueio??0} onChange={e=>updateField('status.bloqueio',num(e.target.value))}/></label><label><span>Esquiva</span><input type="number" value={s.esquiva??10} onChange={e=>updateField('status.esquiva',num(e.target.value))}/></label><label><span>Deslocamento</span><input value={s.deslocamento||''} onChange={e=>updateField('status.deslocamento',e.target.value)}/></label></div></section><section className="ordem-panel"><div className="ordem-panel-actions"><div className="ordem-panel-title"><span>ATAQUES</span><small>teste, dano e detalhes</small></div><button className="ordem-add" onClick={()=>add('ataques',{nome:'',teste:'',dano:'',critico:'',alcance:'',tipo:'',municao:'',desc:''})}>+ Ataque</button></div><div className="space-y-2">{(data.ataques||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="ordem-attack-grid"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome"/><input value={x.teste||''} onChange={e=>patch('ataques',i,'teste',e.target.value)} placeholder="Teste"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><input value={x.critico||''} onChange={e=>patch('ataques',i,'critico',e.target.value)} placeholder="Crítico"/><button onClick={()=>rm('ataques',i)}>×</button></div><div className="ordem-attack-meta"><input value={x.alcance||''} onChange={e=>patch('ataques',i,'alcance',e.target.value)} placeholder="Alcance"/><input value={x.tipo||''} onChange={e=>patch('ataques',i,'tipo',e.target.value)} placeholder="Tipo"/><input value={x.municao||''} onChange={e=>patch('ataques',i,'municao',e.target.value)} placeholder="Munição"/></div><textarea rows="2" value={x.desc||''} onChange={e=>patch('ataques',i,'desc',e.target.value)} placeholder="Efeito / observações"/></div>)}</div></section><section className="ordem-panel"><div className="grid md:grid-cols-2 gap-3"><label><span>Resistências / proteção</span><textarea rows="4" value={data.resistencias||''} onChange={e=>updateField('resistencias',e.target.value)}/></label><label><span>Proficiências</span><textarea rows="4" value={data.proficiencias||''} onChange={e=>updateField('proficiencias',e.target.value)} placeholder="Armas simples, táticas, proteções..."/></label></div></section></div>}

  {tab==='poderes'&&<div className="space-y-3"><section className="ordem-panel"><div className="ordem-panel-actions"><div className="ordem-panel-title"><span>HABILIDADES & PODERES</span><small>origem, classe, trilha e paranormal</small></div><button className="ordem-add" onClick={()=>add('habilidades',{nome:'',tipo:'Poder',custo:'',desc:''})}>+ Poder</button></div><div className="ordem-card-grid">{(data.habilidades||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>rm('habilidades',i)}>×</button></div><div className="grid grid-cols-2 gap-2"><input value={x.tipo||''} onChange={e=>patch('habilidades',i,'tipo',e.target.value)} placeholder="Tipo / origem"/><input value={x.custo||''} onChange={e=>patch('habilidades',i,'custo',e.target.value)} placeholder="Custo"/></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)} placeholder="Descrição / lembrete"/></div>)}</div></section><section className="ordem-panel"><div className="ordem-panel-actions"><div className="ordem-panel-title"><span>RITUAIS</span><small>círculo, elemento e execução</small></div><button className="ordem-add" onClick={()=>add('rituais',{nome:'',circulo:1,elemento:'',execucao:'',alcance:'',duracao:'',resistencia:'',desc:''})}>+ Ritual</button></div><div className="ordem-card-grid">{(data.rituais||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('rituais',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>rm('rituais',i)}>×</button></div><div className="ordem-ritual-grid"><label><span>Círculo</span><input type="number" min="1" value={x.circulo??1} onChange={e=>patch('rituais',i,'circulo',num(e.target.value))}/></label><input value={x.elemento||''} onChange={e=>patch('rituais',i,'elemento',e.target.value)} placeholder="Elemento"/><input value={x.execucao||''} onChange={e=>patch('rituais',i,'execucao',e.target.value)} placeholder="Execução"/><input value={x.alcance||''} onChange={e=>patch('rituais',i,'alcance',e.target.value)} placeholder="Alcance"/><input value={x.duracao||''} onChange={e=>patch('rituais',i,'duracao',e.target.value)} placeholder="Duração"/><input value={x.resistencia||''} onChange={e=>patch('rituais',i,'resistencia',e.target.value)} placeholder="Resistência"/></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('rituais',i,'desc',e.target.value)} placeholder="Efeito / lembrete"/></div>)}</div></section></div>}

  {tab==='inventario'&&<div className="space-y-3"><section className="ordem-panel"><div className="ordem-panel-actions"><div className="ordem-panel-title"><span>INVENTÁRIO</span><small>categoria, espaços e quantidade</small></div><button className="ordem-add" onClick={()=>add('inventario',{nome:'',categoria:'0',espacos:1,quantidade:1,desc:''})}>+ Item</button></div><div className="space-y-2">{(data.inventario||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="ordem-item-grid"><input value={x.nome||''} onChange={e=>patch('inventario',i,'nome',e.target.value)} placeholder="Item"/><input value={x.categoria||''} onChange={e=>patch('inventario',i,'categoria',e.target.value)} placeholder="Cat."/><input type="number" value={x.espacos??1} onChange={e=>patch('inventario',i,'espacos',num(e.target.value))}/><input type="number" value={x.quantidade??1} onChange={e=>patch('inventario',i,'quantidade',num(e.target.value))}/><button onClick={()=>rm('inventario',i)}>×</button></div><textarea rows="2" value={x.desc||''} onChange={e=>patch('inventario',i,'desc',e.target.value)} placeholder="Descrição / observações"/></div>)}</div></section><section className="ordem-panel"><label><span>Anotações</span><textarea rows="7" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section></div>}
 </div>;
}
