import React,{useState} from 'react';
import { ORDEM_ATTRIBUTES, ORDEM_SKILLS } from '../data.js';
const num=v=>Number(v)||0;
const tabs=[['perfil','Perfil'],['pericias','Perícias'],['combate','Combate'],['poderes','Poderes & Rituais'],['inventario','Inventário']];
export default function OrdemCharacterEditor({scope}){
 const {data,updateField,setData,optimizeImageFile,showToast}=scope; const [tab,setTab]=useState('perfil'); if(data?.system!=='ordemParanormal'||data?.type!=='pc')return null;
 const patch=(field,i,key,value)=>{const d=JSON.parse(JSON.stringify(data));const a=Array.isArray(d[field])?d[field]:[];a[i]={...(a[i]||{}),[key]:value};d[field]=a;setData(d);}; const add=(f,o)=>updateField(f,[...(data[f]||[]),o]); const rm=(f,i)=>updateField(f,(data[f]||[]).filter((_,x)=>x!==i));
 const photo=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{updateField('bio.imagem',await optimizeImageFile(f,900,.82));showToast('Retrato atualizado.');}catch{showToast('Não foi possível usar esta imagem.');}};
 const b=data.bio||{},a=data.atributos||{},s=data.status||{};
 return <div className="ordem-sheet p-3 sm:p-5"><div className="ordem-hero"><div><div className="ordem-kicker">Ordem Paranormal RPG • Livro de Regras v1.3</div><h2>Ficha de Agente</h2><p>Investigação • combate • paranormal</p></div><div className="ordem-nex"><span>NEX</span><div><input type="number" min="0" max="100" value={b.nex??5} onChange={e=>updateField('bio.nex',num(e.target.value))}/><b>%</b></div></div></div>
 <div className="ordem-tabs">{tabs.map(([id,n])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{n}</button>)}</div>
 {tab==='perfil'&&<div className="space-y-4"><section className="ordem-card"><div className="grid md:grid-cols-[150px_1fr] gap-4"><div className="ordem-photo">{b.imagem?<img src={b.imagem} alt="Retrato"/>:<div className="ordem-photo-empty">△</div>}<label>Escolher imagem<input type="file" accept="image/*" className="hidden" onChange={photo}/></label>{b.imagem&&<button onClick={()=>updateField('bio.imagem','')}>Remover</button>}</div><div className="grid sm:grid-cols-2 gap-3"><label className="sm:col-span-2"><span>Nome</span><input value={b.nome||''} onChange={e=>updateField('bio.nome',e.target.value)}/></label><label><span>Jogador</span><input value={b.jogador||''} onChange={e=>updateField('bio.jogador',e.target.value)}/></label><label><span>Idade</span><input value={b.idade||''} onChange={e=>updateField('bio.idade',e.target.value)}/></label><label><span>Origem</span><input value={b.origem||''} onChange={e=>updateField('bio.origem',e.target.value)}/></label><label><span>Patente</span><input value={b.patente||''} onChange={e=>updateField('bio.patente',e.target.value)}/></label><label><span>Classe</span><select value={b.classe||''} onChange={e=>updateField('bio.classe',e.target.value)}><option value="">—</option><option>Combatente</option><option>Especialista</option><option>Ocultista</option></select></label><label><span>Trilha</span><input value={b.trilha||''} onChange={e=>updateField('bio.trilha',e.target.value)}/></label></div></div></section>
 <section className="ordem-card"><h3>Atributos</h3><div className="grid grid-cols-5 gap-2">{ORDEM_ATTRIBUTES.map(([k,abbr,n])=><label key={k} className="ordem-attr"><span>{abbr}</span><input type="number" min="0" value={a[k]??1} onChange={e=>updateField(`atributos.${k}`,num(e.target.value))}/><em>{n}</em></label>)}</div></section>
 <section className="ordem-card"><h3>Recursos</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['pv','PV'],['pe','PE'],['san','SAN']].map(([k,n])=><div key={k}><span className="ordem-label">{n}</span><div className="grid grid-cols-2 gap-1"><input type="number" value={s[`${k}Atual`]??0} onChange={e=>updateField(`status.${k}Atual`,num(e.target.value))}/><input type="number" value={s[`${k}Max`]??0} onChange={e=>updateField(`status.${k}Max`,num(e.target.value))}/></div><small>Atual / Máx.</small></div>)}<label><span>Defesa</span><input type="number" value={s.defesa??10} onChange={e=>updateField('status.defesa',num(e.target.value))}/></label><label><span>Deslocamento</span><input value={s.deslocamento||''} onChange={e=>updateField('status.deslocamento',e.target.value)}/></label><label><span>Afinidade</span><input value={data.afinidade||''} onChange={e=>updateField('afinidade',e.target.value)}/></label></div></section></div>}
 {tab==='pericias'&&<section className="ordem-card"><h3>Perícias</h3><p className="ordem-help">Grau de treinamento: destreinado, treinado (+5), veterano (+10) ou expert (+15). “Outros” registra modificadores adicionais.</p><div className="grid sm:grid-cols-2 gap-2 mt-3">{ORDEM_SKILLS.map(([id,n,attr])=>{const x=data.pericias?.[id]||{};return <div className="ordem-skill" key={id}><div><strong>{n}</strong><small>{attr.toUpperCase()}</small></div><select value={x.grau??0} onChange={e=>updateField(`pericias.${id}.grau`,num(e.target.value))}><option value="0">0</option><option value="5">+5</option><option value="10">+10</option><option value="15">+15</option></select><input type="number" value={x.outros??0} onChange={e=>updateField(`pericias.${id}.outros`,num(e.target.value))} title="Outros bônus"/></div>})}</div></section>}
 {tab==='combate'&&<section className="ordem-card"><div className="flex justify-between"><h3>Ataques</h3><button className="ordem-add" onClick={()=>add('ataques',{nome:'',teste:'',dano:'',critico:'',alcance:'',tipo:'',municao:''})}>+ Ataque</button></div><div className="space-y-2">{(data.ataques||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="ordem-row"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome"/><input value={x.teste||''} onChange={e=>patch('ataques',i,'teste',e.target.value)} placeholder="Teste"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><input value={x.critico||''} onChange={e=>patch('ataques',i,'critico',e.target.value)} placeholder="Crítico"/><button onClick={()=>rm('ataques',i)}>×</button></div><div className="grid grid-cols-3 gap-2"><input value={x.alcance||''} onChange={e=>patch('ataques',i,'alcance',e.target.value)} placeholder="Alcance"/><input value={x.tipo||''} onChange={e=>patch('ataques',i,'tipo',e.target.value)} placeholder="Tipo"/><input value={x.municao||''} onChange={e=>patch('ataques',i,'municao',e.target.value)} placeholder="Munição"/></div></div>)}</div><label className="block mt-4"><span>Resistências / observações defensivas</span><textarea rows="4" value={data.resistencias||''} onChange={e=>updateField('resistencias',e.target.value)}/></label></section>}
 {tab==='poderes'&&<div className="space-y-4"><section className="ordem-card"><div className="flex justify-between"><h3>Habilidades & Poderes</h3><button className="ordem-add" onClick={()=>add('habilidades',{nome:'',tipo:'Poder',custo:'',desc:''})}>+ Poder</button></div><div className="grid md:grid-cols-2 gap-2">{(data.habilidades||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>rm('habilidades',i)}>×</button></div><div className="grid grid-cols-2 gap-2"><input value={x.tipo||''} onChange={e=>patch('habilidades',i,'tipo',e.target.value)} placeholder="Tipo / origem"/><input value={x.custo||''} onChange={e=>patch('habilidades',i,'custo',e.target.value)} placeholder="Custo"/></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)} placeholder="Descrição / lembrete"/></div>)}</div></section><section className="ordem-card"><div className="flex justify-between"><h3>Rituais</h3><button className="ordem-add" onClick={()=>add('rituais',{nome:'',circulo:1,elemento:'',execucao:'',alcance:'',duracao:'',resistencia:'',desc:''})}>+ Ritual</button></div><div className="grid md:grid-cols-2 gap-2">{(data.rituais||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('rituais',i,'nome',e.target.value)} placeholder="Nome"/><button onClick={()=>rm('rituais',i)}>×</button></div><div className="grid grid-cols-2 gap-2"><input type="number" min="1" value={x.circulo??1} onChange={e=>patch('rituais',i,'circulo',num(e.target.value))}/><input value={x.elemento||''} onChange={e=>patch('rituais',i,'elemento',e.target.value)} placeholder="Elemento"/><input value={x.execucao||''} onChange={e=>patch('rituais',i,'execucao',e.target.value)} placeholder="Execução"/><input value={x.alcance||''} onChange={e=>patch('rituais',i,'alcance',e.target.value)} placeholder="Alcance"/></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('rituais',i,'desc',e.target.value)} placeholder="Efeito / lembrete"/></div>)}</div></section></div>}
 {tab==='inventario'&&<div className="space-y-4"><section className="ordem-card"><div className="flex justify-between"><h3>Inventário</h3><button className="ordem-add" onClick={()=>add('inventario',{nome:'',categoria:'0',espacos:1,quantidade:1,desc:''})}>+ Item</button></div><div className="space-y-2">{(data.inventario||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="ordem-row"><input value={x.nome||''} onChange={e=>patch('inventario',i,'nome',e.target.value)} placeholder="Item"/><input value={x.categoria||''} onChange={e=>patch('inventario',i,'categoria',e.target.value)} placeholder="Cat."/><input type="number" value={x.espacos??1} onChange={e=>patch('inventario',i,'espacos',num(e.target.value))}/><input type="number" value={x.quantidade??1} onChange={e=>patch('inventario',i,'quantidade',num(e.target.value))}/><button onClick={()=>rm('inventario',i)}>×</button></div><textarea rows="2" value={x.desc||''} onChange={e=>patch('inventario',i,'desc',e.target.value)} placeholder="Descrição / observações"/></div>)}</div></section><section className="ordem-card"><label><span>Anotações</span><textarea rows="8" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section></div>}
 </div>;
}
