import React,{useState} from 'react';
import { ORDEM_ATTRIBUTES } from '../data.js';
const n=v=>Number(v)||0;
export default function OrdemThreatEditor({scope}){
 const {data,updateField,setData}=scope; const [tab,setTab]=useState('perfil'); if(data?.system!=='ordemParanormal'||data?.type==='pc')return null;
 const patch=(f,i,k,v)=>{const d=JSON.parse(JSON.stringify(data));const a=Array.isArray(d[f])?d[f]:[];a[i]={...(a[i]||{}),[k]:v};d[f]=a;setData(d);}; const add=(f,o)=>updateField(f,[...(data[f]||[]),o]);const rm=(f,i)=>updateField(f,(data[f]||[]).filter((_,x)=>x!==i)); const a=data.atributos||{},s=data.status||{};
 return <div className="ordem-sheet p-3 sm:p-5"><div className="ordem-hero ordem-threat-hero"><div><div className="ordem-kicker">Ordem Paranormal RPG v1.3 • Modo Mestre</div><h2>Ameaça / Criatura</h2><p>VD • Elemento • Enigma de Medo</p></div><div className="ordem-nex"><span>VD</span><div><input type="number" min="0" value={data.vd??0} onChange={e=>updateField('vd',n(e.target.value))}/></div></div></div>
 <div className="ordem-tabs">{[['perfil','Perfil'],['acoes','Ações'],['paranormal','Paranormal']].map(([id,x])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{x}</button>)}</div>
 {tab==='perfil'&&<div className="space-y-4"><section className="ordem-card"><div className="grid sm:grid-cols-2 md:grid-cols-4 gap-3"><label className="sm:col-span-2"><span>Nome</span><input value={data.nome||''} onChange={e=>updateField('nome',e.target.value)}/></label><label><span>Categoria</span><input value={data.categoria||''} onChange={e=>updateField('categoria',e.target.value)}/></label><label><span>Elemento</span><input value={data.elemento||''} onChange={e=>updateField('elemento',e.target.value)}/></label><label><span>Tamanho</span><input value={data.tamanho||''} onChange={e=>updateField('tamanho',e.target.value)}/></label><label className="sm:col-span-2 md:col-span-3"><span>Presença Perturbadora</span><input value={data.presencaPerturbadora||''} onChange={e=>updateField('presencaPerturbadora',e.target.value)}/></label></div></section><section className="ordem-card"><h3>Atributos</h3><div className="grid grid-cols-5 gap-2">{ORDEM_ATTRIBUTES.map(([k,abbr])=><label className="ordem-attr" key={k}><span>{abbr}</span><input type="number" min="0" value={a[k]??1} onChange={e=>updateField(`atributos.${k}`,n(e.target.value))}/></label>)}</div></section><section className="ordem-card"><h3>Status</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div><span className="ordem-label">PV</span><div className="grid grid-cols-2 gap-1"><input type="number" value={s.pvAtual??0} onChange={e=>updateField('status.pvAtual',n(e.target.value))}/><input type="number" value={s.pvMax??0} onChange={e=>updateField('status.pvMax',n(e.target.value))}/></div></div><label><span>Defesa</span><input type="number" value={s.defesa??10} onChange={e=>updateField('status.defesa',n(e.target.value))}/></label><label><span>Deslocamento</span><input value={s.deslocamento||''} onChange={e=>updateField('status.deslocamento',e.target.value)}/></label><label><span>Sentidos</span><input value={data.sentidos||''} onChange={e=>updateField('sentidos',e.target.value)}/></label></div></section></div>}
 {tab==='acoes'&&<div className="space-y-4"><section className="ordem-card"><div className="flex justify-between"><h3>Ataques</h3><button className="ordem-add" onClick={()=>add('ataques',{nome:'',teste:'',dano:'',critico:'',alcance:'',desc:''})}>+ Ataque</button></div>{(data.ataques||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="ordem-row"><input value={x.nome||''} onChange={e=>patch('ataques',i,'nome',e.target.value)} placeholder="Nome"/><input value={x.teste||''} onChange={e=>patch('ataques',i,'teste',e.target.value)} placeholder="Teste"/><input value={x.dano||''} onChange={e=>patch('ataques',i,'dano',e.target.value)} placeholder="Dano"/><button onClick={()=>rm('ataques',i)}>×</button></div><textarea rows="2" value={x.desc||''} onChange={e=>patch('ataques',i,'desc',e.target.value)} placeholder="Efeito"/></div>)}</section><section className="ordem-card"><div className="flex justify-between"><h3>Habilidades</h3><button className="ordem-add" onClick={()=>add('habilidades',{nome:'',desc:''})}>+ Habilidade</button></div><div className="grid md:grid-cols-2 gap-2">{(data.habilidades||[]).map((x,i)=><div className="ordem-entry" key={i}><div className="flex gap-2"><input className="flex-1 font-bold" value={x.nome||''} onChange={e=>patch('habilidades',i,'nome',e.target.value)}/><button onClick={()=>rm('habilidades',i)}>×</button></div><textarea rows="3" value={x.desc||''} onChange={e=>patch('habilidades',i,'desc',e.target.value)}/></div>)}</div></section></div>}
 {tab==='paranormal'&&<section className="ordem-card"><div className="grid md:grid-cols-2 gap-3"><label><span>Resistências</span><textarea rows="4" value={data.resistencias||''} onChange={e=>updateField('resistencias',e.target.value)}/></label><label><span>Imunidades</span><textarea rows="4" value={data.imunidades||''} onChange={e=>updateField('imunidades',e.target.value)}/></label><label><span>Vulnerabilidades</span><textarea rows="4" value={data.vulnerabilidades||''} onChange={e=>updateField('vulnerabilidades',e.target.value)}/></label><label><span>Enigma de Medo</span><textarea rows="4" value={data.enigmaMedo||''} onChange={e=>updateField('enigmaMedo',e.target.value)}/></label></div><label className="block mt-3"><span>Anotações do Mestre</span><textarea rows="8" value={data.notas||''} onChange={e=>updateField('notas',e.target.value)}/></label></section>}
 </div>;
}
