const s=v=>String(v??'');
const text=(form,name,value)=>{try{form.getTextField(name).setText(s(value));}catch{}};
const select=(form,name,value)=>{try{form.getDropdown(name).select(s(value));}catch{try{form.getOptionList(name).select(s(value));}catch{}}};
export function fillOrdemPdf(form,item){const b=item.bio||{},a=item.atributos||{},st=item.status||{},g=item.gestao||{};
 text(form,'Personagem',b.nome);text(form,'Jogador',b.jogador);text(form,'AGI',a.agi);text(form,'FOR',a.for);text(form,'INT',a.int);text(form,'PRE',a.pre);text(form,'VIG',a.vig);select(form,'Origem',b.origem);select(form,'Classe',b.classe);text(form,'PV',st.pvMax);text(form,'PV Atuais',st.pvAtual);text(form,'PD',st.pdMax);text(form,'PD Atuais',st.pdAtual);text(form,'PE',st.peMax);text(form,'PE Atuais',st.peAtual);text(form,'SAN',st.sanMax);text(form,'SAN Atual',st.sanAtual);text(form,'DEF',10+(Number(a.agi)||0)+(Number(st.defesaEquip)||0)+(Number(st.defesaOutros)||0));text(form,'DEF - Equip',st.defesaEquip);text(form,'DEF - Outros',st.defesaOutros);text(form,'DESL',st.deslocamento);text(form,'Proteção',item.protecao);text(form,'Resistências',item.resistencias);text(form,'Profissão',b.profissao);
 const nameMap={acrobacia:'Acrobacia',adestramento:'Adestramento',artes:'Artes',atletismo:'Atletismo',atualidades:'Atualidades',ciencias:'Ciências',crime:'Crime',diplomacia:'Diplomacia',enganacao:'Enganação',fortitude:'Fortitude',furtividade:'Furtividade',iniciativa:'Iniciativa',intimidacao:'Intimidação',intuicao:'Intuição',investigacao:'Investigação',luta:'Luta',medicina:'Medicina',ocultismo:'Ocultismo',percepcao:'Percepção',pilotagem:'Pilotagem',pontaria:'Pontaria',profissao:'Profissão',reflexos:'Reflexos',religiao:'Religião',sobrevivencia:'Sobrevivência',tatica:'Tática',tecnologia:'Tecnologia',vontade:'Vontade'};Object.entries(nameMap).forEach(([id,nome])=>{const x=item.pericias?.[id]||{};text(form,`${nome} - Bônus`,(Number(x.grau)||0)+(Number(x.outros)||0));select(form,`${nome} - Treino`,x.grau??0);text(form,`${nome} - Outros`,x.outros??0);});
 (item.ataques||[]).slice(0,5).forEach((x,i)=>{const k=i+1;text(form,`Ataque ${k}`,x.nome);text(form,`Teste ${k}`,x.teste);text(form,`Dano ${k}`,x.dano);text(form,`Crítico/Alcance/Especial ${k}`,[x.critico,x.alcance,x.tipo,x.desc].filter(Boolean).join(' • '));});
 select(form,'NEX',b.nex??0);select(form,'Nível/NEX - Nível',b.nivelExperiencia??1);text(form,'Nível/NEX - NEX',b.nex??0);select(form,'Patente',b.patente||'Recruta');text(form,'Limite de PE/PD',st.limitePePd);text(form,'Anotações',item.notas);text(form,'DT de Rituais',Object.entries(item.dtRituais||{}).map(([k,v])=>v!==''?`${k}º: ${v}`:'').filter(Boolean).join(' | '));text(form,'Pontos de Prestígio',g.prestigio);text(form,'Limite de Itens I',g.limiteItens);select(form,'Limite de Crédito',g.limiteCredito);text(form,'Carga Máx',g.cargaMax);text(form,'Carga Atual',(item.inventario||[]).reduce((t,x)=>t+(Number(x.espacos)||0)*(Number(x.quantidade)||1),0));
 const powers=[...(item.habilidades||[]).map(x=>({...x,__tipo:'Poder'})),...(item.poderesParanormais||[]).map(x=>({...x,__tipo:'Poder Paranormal'})),...(item.rituais||[]).map(x=>({...x,__tipo:'Ritual'}))].slice(0,20);powers.forEach((x,i)=>{const k=i+1;text(form,`Habilidade/Ritual ${k}`,x.nome?`${x.__tipo}: ${x.nome}`:'');text(form,`Habilidade/Ritual - Custo ${k}`,x.custo);text(form,`Habilidade/Ritual - Página ${k}`,x.pagina);text(form,`Habilidade/Ritual - Descritivo ${k}`,[x.elemento,x.requisito,x.execucao,x.alcance,x.duracao,x.resistencia,x.desc].filter(Boolean).join(' • '));});
 (item.inventario||[]).slice(0,22).forEach((x,i)=>{const k=i+1;text(form,`Item ${k}`,x.nome);text(form,`Item - Categoria ${k}`,x.categoria);text(form,`Item - Espaços ${k}`,x.espacos);});
}
