const STORAGE_KEY='dragonbane_saved_characters';
const PDFLIB_CDN='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
const BUTTON_ID='pjlite-rota-zero-pdf-export';

const visible=el=>{if(!el)return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast(message,type='info'){let el=document.getElementById('pjlite-pdf-toast');if(!el){el=document.createElement('div');el.id='pjlite-pdf-toast';Object.assign(el.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'99999',maxWidth:'420px',padding:'10px 14px',borderRadius:'10px',color:'#fff',font:'700 12px system-ui,sans-serif',boxShadow:'0 10px 28px rgba(0,0,0,.28)',transition:'opacity .2s ease'});document.body.appendChild(el);}el.style.background=type==='error'?'#991b1b':type==='success'?'#166534':'#1f2937';el.textContent=message;el.style.opacity='1';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.opacity='0',4800);}
function loadPdfLib(){if(window.PDFLib?.PDFDocument)return Promise.resolve(window.PDFLib);if(loadPdfLib.promise)return loadPdfLib.promise;loadPdfLib.promise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-pjlite-pdflib="1"]');if(old){if(window.PDFLib?.PDFDocument)return resolve(window.PDFLib);old.addEventListener('load',()=>resolve(window.PDFLib),{once:true});old.addEventListener('error',()=>reject(new Error('Não foi possível carregar o gerador de PDF.')),{once:true});return;}const s=document.createElement('script');s.src=PDFLIB_CDN;s.async=true;s.dataset.pjlitePdflib='1';s.onload=()=>window.PDFLib?.PDFDocument?resolve(window.PDFLib):reject(new Error('pdf-lib não iniciou.'));s.onerror=()=>reject(new Error('Não foi possível carregar o gerador de PDF.'));document.head.appendChild(s);});return loadPdfLib.promise;}
function readCharacters(){try{const a=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(a)?a:[];}catch{return[];}}
const stamp=x=>{const t=Date.parse(x?.meta?.updatedAt||x?.meta?.createdAt||'');return Number.isFinite(t)?t:0;};
function currentRotaZero(requireVisible=false){const chars=readCharacters().filter(x=>x?.system==='rotaZero'&&(x?.type||'pc')==='pc');if(!chars.length)return null;const values=new Set(Array.from(document.querySelectorAll('input,textarea,select')).filter(visible).map(x=>String(x.value||'').trim()).filter(Boolean));const matches=chars.filter(x=>x?.bio?.nome&&values.has(String(x.bio.nome).trim()));if(requireVisible&&!matches.length)return null;return [...(matches.length?matches:chars)].sort((a,b)=>stamp(b)-stamp(a))[0]||null;}
function filename(item){const n=String(item?.bio?.nome||'Funcionario').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'Funcionario';return 'PJ_Lite_Rota_Zero_'+n+'.pdf';}
function download(bytes,item){const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=filename(item);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),8000);}
function wrap(font,text,size,maxWidth){const words=String(text||'').split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;}
function drawWrapped(page,font,text,x,y,size,maxWidth,lineHeight,maxLines=99,color){const lines=wrap(font,text,size,maxWidth).slice(0,maxLines);lines.forEach((ln,i)=>page.drawText(ln,{x,y:y-i*lineHeight,size,font,color}));}
function box(page,x,y,w,h,stroke,fill){page.drawRectangle({x,y,width:w,height:h,borderWidth:1,borderColor:stroke,color:fill});}
function label(page,bold,text,x,y,size,color){page.drawText(text,{x,y,size,font:bold,color});}
function field(page,font,bold,name,value,x,y,w,colors){label(page,bold,name,x,y+19,8,colors.ink);page.drawLine({start:{x,y:y+2},end:{x:x+w,y:y+2},thickness:.8,color:colors.line});drawWrapped(page,font,value,x,y+6,9,w,10,1,colors.ink);}
function squareTrack(page,count,filled,x,y,w,h,colors){const gap=6,cw=(w-gap*(count-1))/count;for(let i=0;i<count;i++){page.drawRectangle({x:x+i*(cw+gap),y,width:cw,height:h,borderWidth:1,borderColor:colors.line,color:i<filled?colors.dark:colors.paper});}}
function dataUrlBytes(value){const m=/^data:([^;,]+)?(;base64)?,(.*)$/i.exec(value||'');if(!m)return null;try{const raw=m[2]?atob(m[3]):decodeURIComponent(m[3]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return{bytes,mime:(m[1]||'').toLowerCase()};}catch{return null;}}
async function elementToPng(img){try{if(!img?.complete||!(img.naturalWidth||img.width))await new Promise((res,rej)=>{img.addEventListener('load',res,{once:true});img.addEventListener('error',rej,{once:true});});const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,max=1200,scale=Math.min(1,max/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/png'));return blob?new Uint8Array(await blob.arrayBuffer()):null;}catch{return null;}}
async function portrait(item){const live=Array.from(document.querySelectorAll('.rz-portrait img')).find(visible);if(live){const png=await elementToPng(live);if(png)return{kind:'png',bytes:png};}const value=String(item?.bio?.imagem||'').trim();const d=dataUrlBytes(value);if(d){if(d.mime.includes('png'))return{kind:'png',bytes:d.bytes};if(d.mime.includes('jpeg')||d.mime.includes('jpg'))return{kind:'jpg',bytes:d.bytes};}return null;}
async function drawPortrait(doc,page,item,PDFLib,x,y,w,h,colors){const p=await portrait(item);box(page,x,y,w,h,colors.line,colors.paper);if(!p){page.drawText('FOTO / CRACHA',{x:x+30,y:y+h/2,size:10,font:await doc.embedFont(PDFLib.StandardFonts.Courier),color:colors.muted});return;}try{const img=p.kind==='png'?await doc.embedPng(p.bytes):await doc.embedJpg(p.bytes),dims=img.scale(1),scale=Math.min((w-6)/dims.width,(h-6)/dims.height),iw=dims.width*scale,ih=dims.height*scale;page.drawImage(img,{x:x+(w-iw)/2,y:y+(h-ih)/2,width:iw,height:ih});}catch{}}

function addHeader(page,bold,small,title,colors){page.drawText(small,{x:46,y:790,size:8,font:bold,color:colors.muted});page.drawText(title,{x:46,y:760,size:22,font:bold,color:colors.ink});page.drawLine({start:{x:46,y:748},end:{x:548,y:748},thickness:.8,color:colors.line});}
async function employeePage(doc,item,PDFLib,font,bold,colors){const p=doc.addPage([595,842]);p.drawRectangle({x:0,y:0,width:595,height:842,color:colors.bg});addHeader(p,bold,'FORMULARIO RZ-01 // FICHA DE FUNCIONARIO','Ficha de Funcionario',colors);
 box(p,46,594,330,135,colors.line,colors.paper);field(p,font,bold,'NOME',item.bio?.nome,56,690,96,colors);field(p,font,bold,'CONCEITO',item.bio?.conceito,164,690,96,colors);field(p,font,bold,'FUNCAO / KIT',item.bio?.kit,272,690,94,colors);
 field(p,font,bold,'PULSO (P)',item.atributos?.pulso,56,647,96,colors);field(p,font,bold,'TECNICA (T)',item.atributos?.tecnica,164,647,96,colors);field(p,font,bold,'FIRMEZA (F)',item.atributos?.firmeza,272,647,94,colors);
 field(p,font,bold,'ADRENALINA',(item.recursos?.adrenalina?.atual??'')+'/'+(item.recursos?.adrenalina?.max??''),56,604,96,colors);field(p,font,bold,'FOCO',(item.recursos?.foco?.atual??'')+'/'+(item.recursos?.foco?.max??''),164,604,96,colors);field(p,font,bold,'VITALIDADE',(item.recursos?.vitalidade?.atual??'')+'/'+(item.recursos?.vitalidade?.max??''),272,604,94,colors);
 await drawPortrait(doc,p,item,PDFLib,391,594,157,135,colors);
 [[46,'PANICO',4,(item.panico||[]).filter(Boolean).length],[218,'TRAUMAS',3,(item.traumas||[]).filter(Boolean).length],[390,'INTERFERENCIA 0-6',6,Number(item.interferencia||0)]].forEach(([x,n,c,f])=>{box(p,x,525,158,55,colors.line,colors.paper);label(p,bold,n,x+10,558,8,colors.ink);squareTrack(p,c,f,x+10,536,138,14,colors);});
 box(p,46,377,244,132,colors.line,colors.paper);label(p,bold,'PERICIAS',56,491,8,colors.ink);drawWrapped(p,font,Object.entries(item.pericias||{}).filter(([,v])=>v).map(([k])=>k.replace(/([A-Z])/g,' $1')).join(', '),56,474,9,224,12,8,colors.ink);
 box(p,302,377,246,132,colors.line,colors.paper);label(p,bold,'VANTAGENS / DEFEITOS',312,491,8,colors.ink);const vd=[...(item.vantagens||[]).map(x=>'+ '+x),...(item.defeitos||[]).map(x=>'- '+x)].join('\n');drawWrapped(p,font,vd,312,474,9,226,12,8,colors.ink);
 box(p,46,250,502,112,colors.line,colors.paper);label(p,bold,'INVENTARIO - 4 ESPACOS',56,344,8,colors.ink);(item.inventario||[]).slice(0,4).forEach((v,i)=>{const col=i%2,row=Math.floor(i/2),x=56+col*244,y=304-row*42;box(p,x,y,232,32,colors.line,colors.bg);drawWrapped(p,font,v,x+8,y+12,9,216,10,2,colors.ink);});
 box(p,46,112,244,122,colors.line,colors.paper);label(p,bold,'ANCORA',56,216,8,colors.ink);drawWrapped(p,font,item.ancora,56,198,9,224,12,8,colors.ink);
 box(p,302,112,246,122,colors.line,colors.paper);label(p,bold,'TRAUMAS / GATILHOS / NOTAS',312,216,8,colors.ink);let notes=String(item.notas||'');if(item.contratacao?.horaExtra)notes='HORA EXTRA: +'+Number(item.contratacao?.creditosExtras||0)+' CR\n'+notes;drawWrapped(p,font,notes,312,198,8.5,226,11,9,colors.ink);
 p.drawText('ROTA ZERO // PJ LITE // RZ-01',{x:395,y:28,size:7,font,color:colors.muted});return p;}

function vehiclePage(doc,item,font,bold,colors){const v=item.veiculo||{},p=doc.addPage([595,842]);p.drawRectangle({x:0,y:0,width:595,height:842,color:colors.bg});addHeader(p,bold,'FORMULARIO RZ-02 // FICHA DE VEICULO','Ficha do veiculo',colors);
 [['VEICULO / APELIDO',v.nome,46],['MODELO',v.modelo,218],['PLACA / ID',v.placaId,390]].forEach(([n,val,x])=>{box(p,x,682,158,52,colors.line,colors.paper);field(p,font,bold,n,val,x+10,689,138,colors);});
 [['MANEJO',v.manejo,46],['TRACAO',v.tracao,218],['CASCO',v.casco,390]].forEach(([n,val,x])=>{box(p,x,620,158,48,colors.line,colors.paper);field(p,font,bold,n,val,x+10,627,138,colors);});
 [['COMBUSTIVEL',6,Number(v.combustivel??6),46],['INTEGRIDADE',6,Number(v.integridade??6),218],['AQUECIMENTO',4,Number(v.aquecimento??4),390]].forEach(([n,c,f,x])=>{box(p,x,552,158,54,colors.line,colors.paper);label(p,bold,n,x+10,586,8,colors.ink);squareTrack(p,c,f,x+10,564,138,14,colors);});
 box(p,46,360,244,176,colors.line,colors.paper);label(p,bold,'CARGA / COMPARTIMENTOS',56,518,8,colors.ink);drawWrapped(p,font,v.cargaCompartimentos,56,497,9,224,12,12,colors.ink);
 box(p,302,360,246,176,colors.line,colors.paper);label(p,bold,'UPGRADES / SLOTS',312,518,8,colors.ink);drawWrapped(p,font,v.upgradesSlots,312,497,9,226,12,12,colors.ink);
 box(p,46,120,502,222,colors.line,colors.paper);label(p,bold,'AVARIAS / REPAROS / OBSERVACOES',56,324,8,colors.ink);drawWrapped(p,font,v.avariasReparos,56,302,9,482,12,17,colors.ink);
 p.drawText('ROTA ZERO // PJ LITE // RZ-02',{x:395,y:28,size:7,font,color:colors.muted});return p;}

function turnPage(doc,item,font,bold,colors){const v=item.veiculo||{},p=doc.addPage([595,842]);p.drawRectangle({x:0,y:0,width:595,height:842,color:colors.bg});addHeader(p,bold,'FORMULARIO RZ-03 // VEICULO + TURNO','Registro operacional',colors);
 [['VEICULO',v.nome,46],['PLACA / ID',v.placaId,218],['TURNO / DATA',v.tempoTurno,390]].forEach(([n,val,x])=>{box(p,x,682,158,52,colors.line,colors.paper);field(p,font,bold,n,val,x+10,689,138,colors);});
 [['COMBUSTIVEL',6,Number(v.combustivel??6),46],['INTEGRIDADE',6,Number(v.integridade??6),218],['AQUECIMENTO',4,Number(v.aquecimento??4),390]].forEach(([n,c,f,x])=>{box(p,x,614,158,54,colors.line,colors.paper);label(p,bold,n,x+10,648,8,colors.ink);squareTrack(p,c,f,x+10,626,138,14,colors);});
 label(p,bold,'ENTREGAS',46,590,12,colors.ink);box(p,46,468,502,108,colors.line,colors.paper);drawWrapped(p,font,'Concluidas: '+Number(v.entregas||0)+'   Destino atual: '+String(v.destino||'-'),56,552,10,482,14,3,colors.ink);drawWrapped(p,font,'Rota atual: '+String(v.rotaAtual||'-'),56,510,9,482,12,3,colors.ink);
 box(p,46,254,244,190,colors.line,colors.paper);label(p,bold,'ROTAS / DESVIOS / TEMPO',56,426,8,colors.ink);drawWrapped(p,font,[v.rotaAtual,v.desvios,v.tempoTurno].filter(Boolean).join('\n'),56,406,9,224,12,14,colors.ink);
 box(p,302,254,246,190,colors.line,colors.paper);label(p,bold,'RADIO / MENSAGENS / FREQUENCIAS',312,426,8,colors.ink);drawWrapped(p,font,v.radioMensagens,312,406,9,226,12,14,colors.ink);
 box(p,46,90,502,146,colors.line,colors.paper);label(p,bold,'PISTAS / INCIDENTES / DESPESAS',56,218,8,colors.ink);drawWrapped(p,font,[v.pistasIncidentes,v.despesas&&('Despesas: '+v.despesas)].filter(Boolean).join('\n'),56,198,9,482,12,10,colors.ink);
 p.drawText('ROTA ZERO // PJ LITE // RZ-03',{x:395,y:28,size:7,font,color:colors.muted});return p;}

async function exportPdf(){document.activeElement?.blur?.();await sleep(250);const item=currentRotaZero(false);if(!item)throw new Error('Não encontrei a ficha Rota Zero atual. Salve a ficha e tente novamente.');const PDFLib=await loadPdfLib(),doc=await PDFLib.PDFDocument.create(),font=await doc.embedFont(PDFLib.StandardFonts.Courier),bold=await doc.embedFont(PDFLib.StandardFonts.CourierBold),colors={bg:PDFLib.rgb(.94,.92,.86),paper:PDFLib.rgb(.975,.965,.925),ink:PDFLib.rgb(.08,.12,.10),line:PDFLib.rgb(.31,.37,.33),dark:PDFLib.rgb(.05,.12,.08),muted:PDFLib.rgb(.38,.45,.40)};await employeePage(doc,item,PDFLib,font,bold,colors);if(item.veiculoAtivo){vehiclePage(doc,item,font,bold,colors);turnPage(doc,item,font,bold,colors);}const bytes=await doc.save({useObjectStreams:false});download(bytes,item);return item;}
function editorOpen(){return Array.from(document.querySelectorAll('.rz-sheet')).some(visible)||!!currentRotaZero(true);}
function findToolbar(){const copy=Array.from(document.querySelectorAll('button')).find(b=>visible(b)&&/copiar\s*ficha/i.test((b.textContent||'').replace(/\s+/g,' ').trim()));if(!copy)return null;const toolbar=copy.parentElement;if(!toolbar)return null;const buttons=Array.from(toolbar.querySelectorAll('button'));return buttons.some(b=>/^ZIP$/i.test((b.textContent||'').trim()))&&buttons.some(b=>/salvar/i.test(b.textContent||''))?{copy,toolbar}:null;}
function ensureButton(){let button=document.getElementById(BUTTON_ID);if(!editorOpen()){button?.remove();return;}const found=findToolbar();if(!found)return;const{copy,toolbar}=found;if(!button){button=document.createElement('button');button.id=BUTTON_ID;button.type='button';button.className=copy.className;button.textContent='📄 Baixar PDF';button.title='Gerar os formulários RZ-01 e, se ativo, RZ-02/RZ-03.';button.style.background='rgba(31,69,52,.94)';button.style.whiteSpace='nowrap';button.style.border='1px solid rgba(255,255,255,.28)';button.onclick=async()=>{if(button.dataset.busy==='1')return;const original=button.textContent;button.dataset.busy='1';button.disabled=true;button.textContent='⏳ Gerando PDF...';try{const item=await exportPdf();toast('PDF Rota Zero de '+(item?.bio?.nome||'funcionário')+' baixado.','success');}catch(error){console.error('[PJ Lite Rota Zero PDF]',error);toast(String(error?.message||'Não foi possível gerar o PDF.'),'error');}finally{button.dataset.busy='0';button.disabled=false;button.textContent=original;}};}if(button.parentElement!==toolbar||button.previousElementSibling!==copy)toolbar.insertBefore(button,copy.nextSibling);}
export function installRotaZeroPdfExport(){if(window.__pjliteRotaZeroPdfExportInstalled)return;window.__pjliteRotaZeroPdfExportInstalled=true;let pending=false;const schedule=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;ensureButton();});};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',schedule,{passive:true});addEventListener('focus',schedule,{passive:true});setInterval(ensureButton,800);setTimeout(ensureButton,0);setTimeout(ensureButton,300);setTimeout(ensureButton,1000);}