import { createRoot } from 'react-dom/client';
import './pjlite.css';
import PJLiteApp from './PJLiteApp.jsx';
import './mobile-polish.css';
import './mobile-systems-v8.css';
import './mobile-attrs-v9.css';
import './systems/3det/integration.js';
import './system-icons.js';
import './theme-polish.css';
import { installDragonbanePdfExport } from './systems/dragonbane/index.js';
import { installDndPdfExport } from './systems/dnd5e/index.js';
import { installFabulaPdfExport } from './systems/fabulaUltima/index.js';
import { installSom6PdfExport } from './systems/somDasSeis/index.js';
import { install3DetPdfExport } from './systems/3det/index.js';
import { installSkyfallPdfExport } from './systems/skyfall/index.js';
import { installOrdemPdfExport } from './systems/ordemParanormal/index.js';

createRoot(document.getElementById('root')).render(<PJLiteApp />);
installDragonbanePdfExport();
installDndPdfExport();
installFabulaPdfExport();
installSom6PdfExport();
install3DetPdfExport();
installSkyfallPdfExport();
installOrdemPdfExport();
